version: '2.0'

services:
  activemq:
    image: webcenter/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
  mongo:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - './mongo-data:/data/db'
  webgoat:
    build: webgoat-server/
    command: "sh /home/webgoat/start.sh"
    ports:
      - "8080:8080"
    depends_on:
      [mongo, activemq]
    environment:
      WG_MONGO_PORT: 27017
      WG_MONGO_HOST: mongo
      WG_MQ_HOST: activemq
      WG_MQ_PORT: 61616
      WG_INTERNAL_MONGO: "false"
  webwolf:
    build: webwolf/
    command: "sh /home/webwolf/start.sh"
    depends_on:
      - webgoat
    ports:
      - "8081:8081"
    environment:
      WG_MONGO_PORT: 27017
      WG_MONGO_HOST: mongo
      WG_MQ_HOST: activemq
      WG_MQ_PORT: 61616